networks:
  laravel:
    driver: bridge
volumes:
    database:

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api_laravel
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - db
        networks:
            - laravel

    nginx_laravel:
        image: nginx:alpine
        container_name: nginx_laravel
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/backend/:/etc/nginx/conf.d/
        networks:
            - laravel

    db:
        image: mysql:8.3.0
        container_name: mysql_laravel
        restart: unless-stopped
        env_file: .env
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - database:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

    nginx_frontend:
        image: nginx:alpine
        container_name: nginx_frontend
        restart: unless-stopped
        ports:
            - "8080:8080"
        volumes:
            - ../frontend:/usr/share/nginx/html
            - ./docker/nginx/frontend/:/etc/nginx/conf.d/